DROP PROCEDURE IF EXISTS create_ejb_timer_proc;

DELIMITER //
CREATE PROCEDURE create_ejb_timer_proc
(
IN v_ID  VARCHAR(255),
IN v_TIMED_OBJECT_ID VARCHAR(255), 
IN v_INITIAL_DATE DATETIME, 
IN v_REPEAT_INTERVAL BIGINT, 
IN v_NEXT_DATE DATETIME, 
IN v_PREVIOUS_RUN DATETIME, 
IN v_PRIMARY_KEY VARCHAR(255), 
IN v_INFO TEXT, 
IN v_TIMER_STATE VARCHAR(32), 
IN v_SCHEDULE_EXPR_SECOND VARCHAR(100), 
IN v_SCHEDULE_EXPR_MINUTE VARCHAR(100), 
IN v_SCHEDULE_EXPR_HOUR VARCHAR(100),
IN v_SCHEDULE_EXPR_DAY_OF_WEEK VARCHAR(100), 
IN v_SCHEDULE_EXPR_DAY_OF_MONTH VARCHAR(100), 
IN v_SCHEDULE_EXPR_MONTH VARCHAR(100), 
IN v_SCHEDULE_EXPR_YEAR VARCHAR(100), 
IN v_SCHEDULE_EXPR_START_DATE VARCHAR(100), 
IN v_SCHEDULE_EXPR_END_DATE VARCHAR(100), 
IN v_SCHEDULE_EXPR_TIMEZONE VARCHAR(100), 
IN v_AUTO_TIMER BOOLEAN,
IN v_TIMEOUT_METHOD_DECLARING_CLASS VARCHAR(255),
IN v_TIMEOUT_METHOD_NAME VARCHAR(100),
IN v_TIMEOUT_METHOD_DESCRIPTOR VARCHAR(255), 
IN v_CALENDAR_TIMER BOOLEAN, 
IN v_PARTITION_NAME VARCHAR(100), 
IN v_NODE_NAME VARCHAR(255)
)
BEGIN

	INSERT INTO JBOSS_EJB_TIMER 
	(ID, TIMED_OBJECT_ID, INITIAL_DATE, REPEAT_INTERVAL, NEXT_DATE, PREVIOUS_RUN, PRIMARY_KEY, INFO, TIMER_STATE, SCHEDULE_EXPR_SECOND, SCHEDULE_EXPR_MINUTE, 
	SCHEDULE_EXPR_HOUR, SCHEDULE_EXPR_DAY_OF_WEEK, SCHEDULE_EXPR_DAY_OF_MONTH, SCHEDULE_EXPR_MONTH, SCHEDULE_EXPR_YEAR, SCHEDULE_EXPR_START_DATE, SCHEDULE_EXPR_END_DATE, 
	SCHEDULE_EXPR_TIMEZONE, AUTO_TIMER, TIMEOUT_METHOD_DECLARING_CLASS, TIMEOUT_METHOD_NAME, TIMEOUT_METHOD_DESCRIPTOR, CALENDAR_TIMER, PARTITION_NAME, NODE_NAME) 
	SELECT v_ID, v_TIMED_OBJECT_ID, v_INITIAL_DATE, v_REPEAT_INTERVAL, v_NEXT_DATE, v_PREVIOUS_RUN, v_PRIMARY_KEY, v_INFO, v_TIMER_STATE, v_SCHEDULE_EXPR_SECOND, v_SCHEDULE_EXPR_MINUTE, 
	v_SCHEDULE_EXPR_HOUR, v_SCHEDULE_EXPR_DAY_OF_WEEK, v_SCHEDULE_EXPR_DAY_OF_MONTH, v_SCHEDULE_EXPR_MONTH, v_SCHEDULE_EXPR_YEAR, v_SCHEDULE_EXPR_START_DATE, v_SCHEDULE_EXPR_END_DATE, 
	v_SCHEDULE_EXPR_TIMEZONE, v_AUTO_TIMER, v_TIMEOUT_METHOD_DECLARING_CLASS, v_TIMEOUT_METHOD_NAME, v_TIMEOUT_METHOD_DESCRIPTOR, v_CALENDAR_TIMER, v_PARTITION_NAME, v_NODE_NAME
	FROM dual
	WHERE NOT EXISTS (SELECT * FROM JBOSS_EJB_TIMER
						WHERE TIMED_OBJECT_ID = v_TIMED_OBJECT_ID
							AND PARTITION_NAME = v_PARTITION_NAME
					);

END //
DELIMITER ;
